Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2020-12, with the labels that each got.

#82 [50280] Translate messages on language change
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessageTableViewSource.cs
  NDB.Covid19/NDB.Covid19/Utils/MessageUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/MessageItemViewModel.cs
Labels: ready for merge

#88 [50315] Deleted unused connection causing crash on iOS 13.7
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.xib
Labels: ready for review

#87 [50272] Remove not needed sign
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#89 [50397] Android: Correct scroller padding on consents page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
Labels: ready for review

#90 [50376] Added check for top view controller in order to set correct status ba…
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for review

#93 [50273] Removed URL prefix as this is already present in locales
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
Labels: ready for review

#92 [50357] iOS: Added negative margin InfectionStatusPage scroll view to fix gray line issue with screen zoom on
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
Labels: ready for merge, ready for review

#72 [Cherry-pick] Group cherry pick of update of EN SDK and resending of notifications related changes
  NDB.Covid19/NDB.Covid19.Droid/DroidDependencyInjectionConfig.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Test/DependencyInjectionConfig.cs
  NDB.Covid19/NDB.Covid19.Test/Mocks/LocalNotificationManagerMock.cs
  NDB.Covid19/NDB.Covid19.Test/Mocks/PermissionsMock.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/AbortTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PermissionsTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ReapproveConsentsNotificationTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ResendNotificationTests.cs
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/IOSDependencyInjectionConfig.cs
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Permissions/IOSPermissionsHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationsEnum.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/Interfaces/ILocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Interfaces/IPermissionsHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/Utils/NotificationsHelper.cs
Labels: ready for review

#98 [50314] Add environment name to version number in About page
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage5ViewModel.cs
Labels: ready for review

#97 [50426] Optimize MarkAllAsRead method and add unit test
  NDB.Covid19/NDB.Covid19.Test/Tests/Utils/MessageUtilsTests.cs
  NDB.Covid19/NDB.Covid19/PersistedData/SQLite/IMessagesManager.cs
  NDB.Covid19/NDB.Covid19/PersistedData/SQLite/MessagesManager.cs
  NDB.Covid19/NDB.Covid19/Utils/MessageUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs
Labels: ready for review

#101 [50485] Unify text size accross all pages
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
Labels: ready for review

#103 [50490] Android: Display correct message page header text depending on number of messages
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
Labels: ready for review

#106 [50491] Bugfix/Change request: Removed section from general settings
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: ready for review

#107 [50446] Overlapping buttons on start screen for ios
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
Labels: ready for review

#110 [50231] Text update
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#109 [50501] Android: Fixed wrong placement of scroll bars on consent page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_five.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_three.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_two.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles_welcomepage.xml
Labels: ready for review

#112 [50508] Android: Correct text fields in messages page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
Labels: ready for review

#113 [50516] iOS: Fixed issue where status bar color persisted in consent 2 page
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for review

#115 [50551] Correction of english link to helsenorge.no
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#116 [50314] Do not specify domain for getting environment name
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage5ViewModel.cs
Labels: ready for review

#114 [50504] Android: Align arrow button to text baseline
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_consents.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
Labels: ready for review

#117 [50270] Android: Renamed and reordered buttons in dev tools to match iOS
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
Labels: ready for review

#99 [50422] Fix build warnings
  NDB.Covid19/NDB.Covid19.Droid/Services/DroidDialogService.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/DialogUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/StressUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePagerAdapter.cs
  NDB.Covid19/NDB.Covid19.Test/Mocks/TestPreferencesMock.cs
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19/Interfaces/XamarinEssentials.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#71 [Cherry-pick] Handle 410 response for every view
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/LoadingPageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/ForceUpdateActivity.cs
Labels: ready for review

#121 [50561] Fixed typo in Norwegian bokmål settings page 5 header text
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: ready for merge

#120 [50559] iOS: Wrong header text color in settings page
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: ready for merge

#95 [50448] Adjusted line breaking settings for header label
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePage.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
Labels: ready for merge

#119 [50562] iOS: Inconsistent spacing across pages in burger menu
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
Labels: ready for merge

#125 [50586] Removed unnecessary async in messaging
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs
Labels: ready for review

#122 [50560] Text corrections
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#123 [50569] iOS: Unified horisontal dividers on settings page
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
Labels: ready for review

#128 [50597] iOS: Fixed alignment issue with small screen/large font on onboarding consent page
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
Labels: ready for review

#129 [50608] Implemented minimum date for calendar view to be 21 days back from today
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: ready for merge, ready for review

#132 [50647] Android: Re-added section to general settings
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: ready for review

#134 [50646] iOS: Re-add section to General settings
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.designer.cs
Labels: ready for review

#130 [50637] Dealing with pipeline warnings and code clean
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_feed.axml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_feed_list_item.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_main.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/content_main.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Test/Mocks/LoggingManagerMock.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PermissionsTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/WebServiceStressTests.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
Labels: ready for review

#133 [50516] iOS: Fixed error in status bar color on consent 2 page
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19/Utils/MessagingCenterKeys.cs
Labels: ready for review

#137 [50661] iOS: Missing underline on bottom text of general settings
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: ready for review

#138 [50644] Android: Fix overlapping date in message tile
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_list_element.xml
Labels: ready for review

#140 [50650] Last text update for R1.0
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#142 [50728] Correction of english link
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#135 [50568] Correct arrow back button size and styling
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_consents.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_three.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_two.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
Labels: ready for review

#143 [50728] Update of English texts
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#144 Merge from dev to master on 08.12.2020
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_consents.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_three.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_two.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for merge, ready for review

#145 [Cherry-pick] Fix crash on wake up call
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
Labels: cherry-pick, ready for review

#147 [50812] - Added missing notification texts
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#149 Merge from dev to master on 09.12.2020
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#148 [Cherry-pick] Fix messages after wake up service call
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationType.cs
Labels: cherry-pick, ready for review

#152 [50875] Text update on error page; no match
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#158 [50875] Bugfix - Update of header text for nynorsk on error page
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#61 Added time skew to JWT-validation
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
Labels: ready for review

#161 [51084] Bugfix, Android - Accessibility, added app title to main page
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for merge, ready for review

#165 [50843] Bugfix: Removed EU and EEA from English text
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#163 Merge from dev to master on 14-12-2020
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for merge, ready for review

#168 [51185] & [51196] - Added screen reader text for FHI logo
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/Settings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#169 [50796], [50839], [50870], [50871], [50882], [50982] Bugfixes - Text update
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for merge, ready for review

#170 [51167] iOS: Add burger menu button to focus guide
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for review

#166 [50727] Android: Changed logic so user is navigated to main page if denying key upload
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/LoadingPageActivity.cs
Labels: ready for merge

#167 [50975] Android: Fixed issue where ID-porten login is displayed twice
  NDB.Covid19/NDB.Covid19.Droid/OAuth2/AuthUrlSchemeInterceptorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
Labels: draft

#174 [51185]: Updated English text
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#175 [50795] Android: Implemented page with a loading spinner to display to users while authenticating
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/OAuth2/AuthUrlSchemeInterceptorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/spinner_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/SpinnerPageActivity.cs
Labels: ready for review

#176 [50870] - Text update according to changes
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for merge, ready for review

#177 Merge into master to keep updated with dev
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/OAuth2/AuthUrlSchemeInterceptorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/spinner_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/SpinnerPageActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#182 Enable Interoperability features
  NDB.Covid19/NDB.Covid19/Utils/ConsentsHelper.cs
Labels: ready for review

#180 [50989] iOS: Adjusted country questionnaire page to fit Norwegian design
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxChecked.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxChecked.imageset/checkboxChecked.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxChecked.imageset/checkboxChecked@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxChecked.imageset/checkboxChecked@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxUnchecked.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxUnchecked.imageset/Rectangle 300.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxUnchecked.imageset/Rectangle 300@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/CheckboxUnchecked.imageset/Rectangle 300@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/combinedShape.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/combinedShape@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/combinedShape@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/checkboxUnfilled.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/checkboxUnfilled@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/checkboxUnfilled@3x.png
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/CountryTableCell.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/CountryTableCell.xib
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountries.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
Labels: R2.0, interoperability, ready for review

#181 [50988] iOS: Adjusted questionnaire flow to include country selection page
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
Labels: R2.0, interoperability

#186 [51294] Android: Countries questionnaire
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/country_view.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/questionnaire_countries.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireAdapters/QuestionnaireCountriesSelectionAdapter.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
Labels: R2.0, interoperability, ready for review

#183 [50986] iOS: Changed What is new page layout to Norwegian design
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/WelcomePageWhatIsNewViewModel.cs
Labels: R2.0, interoperability, ready for review

#193 Update of version number for R1.0.1
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: ready for review

#199 [50812] Bugfix - Text for notifications
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#189 [Cherry-pick] [100266] Android: Fix the same notification id
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
Labels: cherry-pick, ready for review

#202 iOS: Add consents 3 page
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
Labels: interoperability, ready for review

#192 [50565] iOS: Unified text spacing in consent views
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
Labels: r1_x, ready for review

#190 [51371] iOS: Show inactive notification on non active state
  NDB.Covid19/NDB.Covid19.iOS/Permissions/IOSPermissionManager.cs
  NDB.Covid19/NDB.Covid19.iOS/Permissions/IOSPermissionsHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: cherry-pick, r1_x, ready for review

#184 [51207] Android: Removed accessibility text on message icon
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: r1_x, ready for review

#188 [51206] Android: Implemented colored outline on main page button when focused
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
Labels: r1_x, ready for review

#179 [51180] Android: Fix Samsung not redirecting to bluetooth settings
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
Labels: r1_x, ready for review

#185 [51213] Marked all headings as headings for accessibility purposes
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/HeadingAccessibilityDelegate.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
Labels: r1_x, ready for review
