Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2020-11, with the labels that each got.

#8 [49451] Fix crash on link click
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for merge, ready for review

#6 Update of texts
  NDB.Covid19/NDB.Covid19/Enums/NotificationsEnum.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for merge, ready for review

#10 [49436] Fixed bug where cellular usage preference is not persisted/displayed correctly
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: ready for merge, ready for review

#9 Removed not needed section from "How it works" in burgermenu
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage2ViewModel.cs
Labels: ready for merge, ready for review

#12 Fixed null values in json causing issues
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for merge, ready for review

#11 Add app center diagnostics for alpha builds
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
Labels: ready for review

#7 [48560] Disable consents functionality for release 1
  NDB.Covid19/NDB.Covid19.Droid/Utils/NavigationHelper.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/NavigationHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomeViewController.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/Utils/ConsentsHelper.cs
Labels: ready for review

#13 Fixed redirect url for android, reworked Keychain access group naming
  NDB.Covid19/NDB.Covid19.Droid/OAuth2/AuthUrlSchemeInterceptorActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Entitlements-prod.plist
  NDB.Covid19/NDB.Covid19.iOS/Entitlements.plist
Labels: ready for merge, ready for review

#15 Changed to correct activate/deactivate button title text on iOS
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for merge, ready for review

#14 Update links with the latest version
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#17 [48446] - iOS, Questionnaire page
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/InformationIcon.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/InformationIcon.imageset/informationIcon1x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/InformationIcon.imageset/informationIcon2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/InformationIcon.imageset/informationIcon3x.png
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/informationIcon.imageset/informationIcon1x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/informationIcon.imageset/informationIcon2x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/informationIcon.imageset/informationIcon3x.png
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/Questionnaire.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
Labels: ready for merge, ready for review

#18 [49538] - Color changes and shadows
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_five.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
  NDB.Covid19/NDB.Covid19.iOS/LaunchScreen.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
Labels: ready for review

#19 [49320] Implemented scoll bar flashing on welcome pages
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThree.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
Labels: ready for merge, ready for review

#20 [Feature/48402] no messages view iOS
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePage.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.designer.cs
Labels: ready for merge, ready for review

#22 Update README.md
  README.md
Labels: ready for merge, ready for review

#21 Android: Implement Messages view
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/messages_border.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/message_title.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_list_element.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/MessageItemViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs
Labels: ready for review

#25 [48511] Force users to login to ID porten
  NDB.Covid19/NDB.Covid19/OAuth2/CustomOAuth2Authenticator.cs
Labels: ready for merge, ready for review

#28 [49894] - Changed text color for developer tools
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
Labels: ready for review

#26 [49545] - Android, Modified consent 1 page layout
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_paragraph.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/ConsentViewModel.cs
Labels: ready for review

#31 [49544] - iOS, styling of consent 1 page
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
Labels: ready for review

#32 [49901] Adjusted spacing on welcome pages
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThree.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/Welcome.storyboard
Labels: ready for review

#29 Auto restart on language change
  NDB.Covid19/NDB.Covid19.Droid/DroidDependencyInjectionConfig.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Utils/DroidResetViews.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/IOSDependencyInjectionConfig.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/IOSResetViews.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19/Interfaces/IResetViews.cs
  NDB.Covid19/NDB.Covid19/ViewModels/MessageItemViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: ready for review

#36 [49863] Updated text styling of consent pages
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_paragraph.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
Labels: ready for review

#38 Fix to font crash in StyleUtils on iOS
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
Labels: ready for merge

#35 [49937] Add handling of html tags to error pages
  NDB.Covid19/NDB.Covid19.iOS/Views/ErrorStatus/ErrorPageViewController.cs
Labels: ready for review

#40 [49816] Android - Added logo to start page and main page
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/app_logo.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/app_logo.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/app_logo.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: ready for review

#37 Removed unused variables
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
Labels: ready for review

#34 [49863] Update of texts
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#42 [49995] Bugfix font crash for the italic font
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
Labels: ready for review

#43 [49782] Make underline less thick
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsItemCell.cs
Labels: ready for review

#44 [49815 and 49817] Feature add logo to start and infection status pages on iOS
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/FHISmittestoppLogo.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/FHISmittestoppLogo.imageset/FHI_Smittestopp_App_Logo_Aktiv_Inaktiv@1x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/FHISmittestoppLogo.imageset/FHI_Smittestopp_App_Logo_Aktiv_Inaktiv@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/FHISmittestoppLogo.imageset/FHI_Smittestopp_App_Logo_Aktiv_Inaktiv@3x.png
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#39 [49972] Android: Unify pages with the same margins
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/error_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_list_element.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/proximity_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/proximity_sublayout.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/questionnaire_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/registered_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_consents.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
Labels: ready for review

#46 [50047] Android: Add Last updated label to messages view
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
Labels: ready for merge

#30 [48404] Implemented message page iOS
  NDB.Covid19/NDB.Covid19.iOS/Utils/ColorHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePage.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.xib
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessageTableViewSource.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/MessagesViewModel.cs
Labels: ready for review

#48 [49863] Text update
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#49 Fix no underline in settings
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
Labels: ready for review

#45 [50024] iOS: Unified layouts in settings and welcome pages
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFour.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOne.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThree.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwo.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/Welcome.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomeViewController.designer.cs
Labels: ready for review

#52 [50145] iOS: Fixed issue with background color in InfectionStatus page
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for merge

#54 [49849] Add padding to the bottom of Infection Status page
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
Labels: ready for review

#55 [50146] iOS: Fixed issue where status bar color from InfectionStatus page persiste…
  NDB.Covid19/NDB.Covid19.iOS/Utils/ColorHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for review

#57 [49903] Fixed margin issue on consent page appearing on iPhone SE Gen 1
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
Labels: ready for review

#58 [50160] Bugfix - Fixed url in 'About' page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#59 [50156] iOS: Unify links behaviour in Settings
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/OpenTextViewUrlInWebviewDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: ready for review

#56 [50153] Bugfix, iOS - Added italic font to consent 1 pages
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
Labels: ready for review

#66 [50138] iOS: Implemented custom back button with larger tap area and placed it in …
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Views/CustomSubclasses/CustomBackButton.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFour.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOne.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThree.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwo.storyboard
Labels: ready for review

#68 [50220] Bugfix - Removed space in text
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: ready for merge, ready for review

#73 Added tracking of error for submit batches
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
Labels: ready for merge, ready for review

#62 Fix TransmissionRiskCalculationTest
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/TransmissionRiskCalculationTest.cs
Labels: ready for review

#74 [50148] - iOS, logo
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/100.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/1024-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/1024.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/120-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/120.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/120_3x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/152.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/167.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/172.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/180-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/180.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/196.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/216.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/29.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/40-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/40-2.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/40.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/48.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/55.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/58-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/58-2.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/58.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/60.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/76.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/80-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/80-2.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/80.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/87-1.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/87.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/88.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/Spotlight.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/AppIconNO.appiconset/Spotlight2x.png
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/FHISmittestoppLogo.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/InformationIcon.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
Labels: ready for review

#67 [50206] iOS: Corrected scrollbar position
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
Labels: ready for merge, ready for review

#75 [Cherry-pick] Fixed a bug where a badge persists after opening the app for resent notification
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: ready for merge, ready for review

#70 [Cherry-pick] Prevent app restricted error
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#76 [50237] Android: Added border and new background color to tiles
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/infection_status_tile_border.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
Labels: ready for review

#81 [50255] iOS: Add italic style section to welcome consents page
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
Labels: ready for review

#80 [feature/48649] IOS: Implemented second button on start page for selecting Nynorsk
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InitializerViewModel.cs
Labels: ready for review

#83 [48633] Updated start screen with button to start the app in nynorsk
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InitializerViewModel.cs
Labels: ready for review

#84 [50285] New notification icon for Android
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_notification.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_notification.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_notification.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxxhdpi/ic_notification.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_notification.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationManager.cs
Labels: ready for review
