Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-01, with the labels that each got.

#203 [50447] Correct not fitting texts on iOS
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
Labels: r1_x, ready for review

#178 [51194] Android: Correct permissions flow
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: r1_x, ready for review

#191 [51211] How it works page - better support for screen readers
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage2ViewModel.cs
Labels: do not merge, r1_x, ready for review

#206 [50565] iOS: Fixed inconsistent margins in consent 2 page
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
Labels: r1_x, ready for review

#212 [Feature/51622] Adjusted what is new text
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/WelcomePageWhatIsNewViewModel.cs
Labels: interoperability, ready for review

#211 Add bullet to welcome page one
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StressUtils.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOne.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/WelcomeViewModel.cs
Labels: interoperability, ready for review

#213 [Feature/51632] Adjusted country questionnaire text
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: interoperability, ready for review

#208 Add consents flag to POST diagnostickeys request
  NDB.Covid19/NDB.Covid19/Models/SelfDiagnosisSubmissionDTO.cs
Labels: interoperability, ready for review

#214 [51605] Do not allow user to skip consents after notification click
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
Labels: interoperability, ready for review

#217 Revert "[51211] How it works page - better support for screen readers"
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage2ViewModel.cs
Labels: r1_x, ready for review

#216 [Feature/51297] Added section to how it works page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage2ViewModel.cs
Labels: interoperability, ready for review

#150 [ExPR 003] Add Anonymous tokens and "Initiator"
  NDB.Covid19/NDB.Covid19.Test/Helpers/ApiStubHelper.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/AbortTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PushKeysTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/WebServiceTests.cs
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/Models/UserDefinedExceptions/WebServiceHttpException.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: enhancement, ready for merge

#218 [Feature/51601] Both platforms: Updated layout and flow of countries consent
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/countries_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/CustomSubclasses/DefaultBorderButton.cs
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
Labels: interoperability, ready for review

#219 EFGS Text update
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: interoperability, ready for review

#220 EFGS text update
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
Labels: interoperability, ready for review

#221 [51299] New terms notification flow
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Test/Mocks/LocalNotificationManagerMock.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ReapproveConsentsNotificationTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
Labels: enhancement, interoperability, ready for review

#224 [51884] Android: Correct vertical margins between headers and content
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
Labels: r1_x, ready for review

#225 [51677] [51678] [51739] Text updates
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#226 [51783] [51784] Adjusted text of header and button in consent 3 dialog
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: ready for review

#227 [51958] Removed unused HTML tags
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#229 Change colors on Force Update page
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/force_update.xml
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdate.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdateViewController.cs
Labels: R2.0, interoperability, ready for review

#233 Merge dev_r1_x into dev
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/HeadingAccessibilityDelegate.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#234 Merge dev into dev-efgs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/HeadingAccessibilityDelegate.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Helpers/ApiStubHelper.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/AbortTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PushKeysTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/WebServiceTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/Models/UserDefinedExceptions/WebServiceHttpException.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: ready for review

#230 [51371] iOS: Removed disabling of EN if it's enabled but not running
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: bug, ready for merge

#239 Removed unused string from how it works page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage2ViewModel.cs
Labels: ready for review

#237 Adjusted force update page design
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/force_update.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/ForceUpdateActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdate.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdateViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdateViewController.designer.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ForceUpdateViewModel.cs
Labels: ready for review

#241 [51206] Increased stroke width on focused buttons
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
Labels: r1_x, ready for merge, ready for review

#242 Implemented button for navigating to force update page from dev tools
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperTools.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.designer.cs
Labels: interoperability, ready for review

#240 [52112] Added missing consent notification text
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#243 [52124] Releasing semaphor on dialog cancel
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: ready for review

#244 [52149] [52151] Text fixes
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: r1_x, ready for review

#245 [52125] Increased spacing in what is new page
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard
Labels: interoperability, ready for review

#246 [52221] Enabled auto restart on language change
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.0, ready for review

#247 [51371] iOS: Fixed missing notification if bluetooth is disabled
  NDB.Covid19/NDB.Covid19.iOS/Utils/BackgroundServiceHandler.cs
Labels: r1_x, ready for review

#249 Merge dev to master
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/HeadingAccessibilityDelegate.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Helpers/ApiStubHelper.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/AbortTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PushKeysTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/WebServiceTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/BackgroundServiceHandler.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/Models/UserDefinedExceptions/WebServiceHttpException.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: ready for review

#250 Updated version number for R1.0.2
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: ready for review

#251 Merge version bump from dev into master
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: ready for review

#248 [51632] Updated text in country questionnaire page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: R2.0, ready for review

#252 Bokmål text updates
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: ready for review

#254 [51214] Added accessibility label to main page logo
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: r1_x, ready for review

#258 Adjusted flow for sharing keys
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
Labels: R2.0, interoperability, ready for review

#263 Merge dev into dev efgs
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_default_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_secondary_button.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Utils/BackgroundServiceHandler.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: ready for review

#257 [feature/51622] Adjusted what is new flow and texts
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ReapproveConsentsNotificationTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: R2.0, interoperability, ready for review

#261 [52462] Added accesibility label to logos on initializer page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.designer.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InitializerViewModel.cs
Labels: R2.0, ready for review

#260 [Feature/52342] Android: Adjusted all views to support landscape mode
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_five.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_three.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_two.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles_welcomepage.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/LoadingPageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/SpinnerPageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/ForceUpdateActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
Labels: R2_x, ready for review

#259 [feature/52350] iOS: Adjusted all views to support landscape mode
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountries.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ErrorStatus/ErrorPage.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOne.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/Welcome.storyboard
Labels: R2_x, ready for review

#267 Bump version number to 2.0
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: R2.0, ready for review

#266 [Feature/50606] App overrules user's symptom onset if test date is earlier
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2_x, ready for review

#271 [52676] iOS: Adjusted font size in What is new page
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
Labels: R2.0, ready for review

#269 [52661, 52538] Bypass location check from Android 11 (API 30) and above
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
Labels: do not merge, ready for review

#274 Merge dev into master
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
Labels: ready for review

#275 [50983],[52069],[52070] - Consent pages, update of layout and text
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/countries_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/ConsentViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
Labels: R2.0, ready for review

#277 [52792] Fixed logic regarding next button click in questionnaire page
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2_x, ready for review

#276 [feature/51293] Adjusted country fetching after backend changes
  NDB.Covid19/NDB.Covid19.Test/Tests/Utils/LanguageTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ViewModels/QuestionnaireCountriesViewModelTests.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CountryDetailsDTO.cs
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireCountriesViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/CountryListService.cs
Labels: R2.0, interoperability, ready for review

#278 [52840] Added missing text in and rearranged views on consent page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/ConsentViewModel.cs
Labels: R2.0, ready for review

#283 Adjust prebuild scripts
  NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
Labels: is:enhancement, ready for review

#282 [52986] Pulling all batch types in any situation
  NDB.Covid19/NDB.Covid19.Test/Helpers/ZipDownloaderHelper.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PullKeysParamsTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PullKeysTests.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/PullKeysParams.cs
Labels: R2.0, interoperability, ready for review

#286 [53043] iOS: Adjusted spacing in what is new page
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard
Labels: R2.0, interoperability, ready for review

#285 [52883] Fixed spelling issue
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: R2.0, ready for review

#273 [Feature/52349] Implemented link button to accessibility statement in about page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage5ViewModel.cs
Labels: R2_x, ready for review

#289 [53099] Android: Ignore heading accessibility delegate on Android 9 and below
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
Labels: ready for review

#298 [53102] Android: Fixed screen reader issue in what is new page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_bullet.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
Labels: R2.0, ready for review

#300 [Feature/52349] Adjusted appearance of accessibility statement link and added english link
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2_x, ready for review

#302 [53142] Fixed flashing of dummy text when loading countries
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
Labels: R2.0, ready for review

#301 [feature/53090] iOS: Add section about "Personvernombud" and change appearance of privacy policy button
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
Labels: R2_x, ready for review
