Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-06, with the labels that each got.

#544 [Issue 179] Bugfix - alignment of dialog title for Arabic and Urdu
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R3.1, ready for review

#543 Bugfix/battery optimization dialog logic / update keys logic
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BatteryOptimisationUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
Labels: R3.1

#545 [Issue 183] Changing logic of displaying dialog
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R3.1, ready for review

#547 Bugfix - pulling keys when EN is active
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R3.1, ready for review

#548 Merge dev R3.1 into dev
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/background_activity_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/spinner_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Services/TimedReminderForegroundService.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BatteryOptimisationUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/ForegroundServiceHelper.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Mocks/LocalNotificationManagerMock.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/HoursPickerModel.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationType.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationsEnum.cs
  NDB.Covid19/NDB.Covid19/Interfaces/ILocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/NotificationChannelsViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: R3.1, ready for review

#550 Bugfix [IOS] - Fix infectionstatuspage in horizontal and statusbar color
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
Labels: R3.1, ready for review

#549 [56004] [Issue 57] - Automatic update of certificate / identity server mock to test functionality
  NDB.Covid19/IdentityServerMock/Data/ClientManager.cs
  NDB.Covid19/IdentityServerMock/Data/ResourceManager.cs
  NDB.Covid19/IdentityServerMock/IdentityServerMock.csproj
  NDB.Covid19/IdentityServerMock/Program.cs
  NDB.Covid19/IdentityServerMock/Startup.cs
  NDB.Covid19/IdentityServerMock/appsettings.Development.json
  NDB.Covid19/IdentityServerMock/appsettings.json
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/OAuth2/IdentityServerTest.cs
  NDB.Covid19/NDB.Covid19.sln
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
Labels: R3.1, ready for review

#553 [Bugfix] [58584] - Changes in translation
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R3.1, ready for review

#554 Merge dev R3.1 into dev
  NDB.Covid19/IdentityServerMock/Data/ClientManager.cs
  NDB.Covid19/IdentityServerMock/Data/ResourceManager.cs
  NDB.Covid19/IdentityServerMock/IdentityServerMock.csproj
  NDB.Covid19/IdentityServerMock/Program.cs
  NDB.Covid19/IdentityServerMock/Startup.cs
  NDB.Covid19/IdentityServerMock/appsettings.Development.json
  NDB.Covid19/IdentityServerMock/appsettings.json
  NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/OAuth2/IdentityServerTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.sln
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
Labels: R3.1, ready for review

#555 Merge dev into master
  NDB.Covid19/IdentityServerMock/Data/ClientManager.cs
  NDB.Covid19/IdentityServerMock/Data/ResourceManager.cs
  NDB.Covid19/IdentityServerMock/IdentityServerMock.csproj
  NDB.Covid19/IdentityServerMock/Program.cs
  NDB.Covid19/IdentityServerMock/Startup.cs
  NDB.Covid19/IdentityServerMock/appsettings.Development.json
  NDB.Covid19/IdentityServerMock/appsettings.json
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/background_activity_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/spinner_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Services/TimedReminderForegroundService.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BatteryOptimisationUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/ForegroundServiceHelper.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.Test/Mocks/LocalNotificationManagerMock.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/OAuth2/IdentityServerTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/HoursPickerModel.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.sln
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationType.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationsEnum.cs
  NDB.Covid19/NDB.Covid19/Interfaces/ILocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/NotificationChannelsViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: R3.1, ready for review

#556 Increased version number to 3.2
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: R3.2, ready for review

#557 Merging latest dev R3.1 to R3.2
  NDB.Covid19/IdentityServerMock/Data/ClientManager.cs
  NDB.Covid19/IdentityServerMock/Data/ResourceManager.cs
  NDB.Covid19/IdentityServerMock/IdentityServerMock.csproj
  NDB.Covid19/IdentityServerMock/Program.cs
  NDB.Covid19/IdentityServerMock/Startup.cs
  NDB.Covid19/IdentityServerMock/appsettings.Development.json
  NDB.Covid19/IdentityServerMock/appsettings.json
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/background_activity_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/spinner_dialog.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Services/BackgroundNotificationBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Services/TimedReminderForegroundService.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BatteryOptimisationUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/ForegroundServiceHelper.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.Test/Mocks/LocalNotificationManagerMock.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/OAuth2/IdentityServerTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/HoursPickerModel.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.sln
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationType.cs
  NDB.Covid19/NDB.Covid19/Enums/NotificationsEnum.cs
  NDB.Covid19/NDB.Covid19/Interfaces/ILocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/OAuth2/AuthenticationManager.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/NotificationChannelsViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: R3.2, ready for review

#558 [57305] [Issue 187] | [57003] [Bugfix] - Changes to key figures page and bugfix of hyphenation in norwegian language
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CovidStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R3.2, ready for review

#563 Bugfix - Screen reader key figures page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
Labels: R3.2, ready for review

#564 Bugfix - Key figures page
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: R3.2

#565 [Android] Bugfix screen reader vaccinations 1. dose
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R3.2, ready for review

#566 Fix links on key figures page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
Labels: R3.2, ready for review

#567 [Issue 188 - Android IOS] [Bugfix 58909] - Questionnaire button infection status page and bugfix text alignment
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_infection_status_survey_border.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: R3.2, ready for review

#568 [Bugfix][Issue 188] - Android/IOS Accessibility trait for survey button
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: R3.2, ready for review

#569 Merge dev R3.2 into dev
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_infection_status_survey_border.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CovidStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: R3.2, ready for review

#570 Merge dev into master
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_survey.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_infection_status_survey_border.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/ic_survey.imageset/External_white@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CovidStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: R3.2, ready for review
