Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-03, with the labels that each got.

#387 [53774] update main page todays numbers SubHeader
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: R2.2, ready for review

#389 [53776-53777] removed death number from shared code
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/FHIStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R2.2, ready for review

#388 [54477, 54478] Android: Add Lithuanian to language selection page and general settings page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/language_selection.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/LanguageSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
Labels: R2.2, ready for review

#391 [Feature/54611] Implemented clickable email addresses and phone numbers
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#397 [54717] iOS: Marked headings as headings
  NDB.Covid19/NDB.Covid19.iOS/Utils/ConsentHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ErrorStatus/ErrorPageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
Labels: R2.2, ready for review

#392 [54235] Android: Replaced custom textview with standard for better RTL support
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
Labels: R2.2, ready for review

#398 [54718] Marked links as links
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ForceUpdate/ForceUpdateViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessageTableViewSource.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage5ViewModel.cs
Labels: R2.2, ready for review

#395 [54661] Android: Restructured daily numbers layout for better screen reader support
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
Labels: R2.2, ready for review

#399 [54714, 54708] Android: Fixed page order announcement and accessibility traversal in welcome pages
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#393 [54663, 54625] iOS: Reduced spacing and corrected accessibility label in daily numbers page
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
Labels: R2.2, ready for review

#400 Updated text for Tigrinya
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R2.2, ready for review

#394 [53776, 53777] added links to all subtexts on todays numbers page
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: R2.2, ready for review

#406 [54715] Adjusted link color for better contrast
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
  NDB.Covid19/NDB.Covid19.iOS/Utils/ColorHelper.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
Labels: R2.2, ready for review

#407 [54709, 54713, 54234] Various screenreader bugs and fixed link in arabic language
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/countries_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/error_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/information_and_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/questionnaire_countries.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/questionnaire_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/registered_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
Labels: R2.2, ready for review

#408 Added latest version of English language
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: R2.2, ready for review

#405 [54710, 54711, 54712] iOS: Fixed various screen reader bugs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2.2, ready for review

#409 [54757, 54759] Screen reader bugs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R2.2, ready for review

#411 [54800] Android: Fixed status bar color
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R2.2, ready for review

#412 [54801] iOS: Fixed page number announcements
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFour.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThree.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomeViewController.cs
Labels: R2.2, ready for merge

#414 [54812] Fixed spelling errors in Norwegian consent two text
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for merge

#413 [Feature/53771] Replaced close button with back button on key numbers page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/WelcomePageTools.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersLoadingPage.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsAbout.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsWithdrawConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsViewModel.cs
Labels: R2.2, ready for merge

#416 Added latest version of all texts
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#418 [54854] Updated key numbers source link to english page for all non-norwegian languages
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#420 Bugfix/build error due to missing text android
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R2.2, ready for merge

#417 [54853] Removed reference to removed death numbers
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#421 Added missing english texts
  NDB.Covid19/NDB.Covid19/Locales/en.json
Labels: R2.2, ready for review

#423 [54928] Key Figures header iOS 12.5
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
Labels: R2.2, ready for review

#415 IOS: update consent one - move sticky components to bottom
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
Labels: R2.2, ready for review

#435 [55018] Updated Arabic link
  NDB.Covid19/NDB.Covid19/Locales/ar.json
Labels: R2.2, ready for review

#429 [55020] Android: Added layout direction check to key numbers page
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R2.2, ready for review

#434 [55035] iOS: Changed to natural text alignment in key numbers box
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
Labels: R2.2, ready for review

#432 [55029] Android: Corrected text alignment in settings menu
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
Labels: R2.2, ready for review

#431 [55023] iOS: Corrected text alignment in settings menu
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsItemCell.cs
Labels: R2.2, ready for review

#430 [55021] Android: Corrected text alignment of contact information on consent 1 page
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
Labels: R2.2, ready for review

#425 [54923, 54936, 54966] Various key numbers UI and text bugs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_bottom.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_mid.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_top.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#401 [feature/53790] Enabled and adjusted key numbers backend integration
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/AppStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/DailyNumbersDTO.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/FHIStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R2.2, ready for review

#428 [54979] Corrected casing in Bokmål and Nynorsk
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#439 [54954] Unified wording of key numbers total text in Norwegian
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: R2.2, ready for review

#442 [53767] Added nuget package and updated version
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/TempNugetFeed/Xamarin.ExposureNotification.0.16.0-alpha.nupkg
Labels: R2.3, ready for review

#443 Added mock implementation of GetDailySummaryConfigurationAsync
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
Labels: R3.0, ready for merge

#440 [53781] iOS: Screen reader support for the new page "Dagens tall"
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
Labels: R2.2, ready for review

#441 [54709] Make headers be read first instead of close buttons in report infected flow
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/Questionnaire.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountries.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompleted.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
Labels: R2.2, ready for review

#448 [55233] Updated Urdu texts and verified text alignments
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#444 [53767] Updated DevTools to print and fetch v2 configs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
Labels: R3.0, ready for review

#449 [55323] Fix crash on countries list not being loaded
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
Labels: R2.2, ready for review

#450 [55362] Updated Tigrinya texts
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R2.2, ready for review

#446 Initial implementation of risk calculation in EN v2
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ExposureDetectedTests.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
Labels: R3.0, ready for review

#451 Rework mock configuration for EN API v2
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
Labels: R3.0, ready for review

#445 Implemented DTO and method for fetching DailySummaryConfiguration from backend
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Models/DailySummaryConfigurationDTO.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R3.0, ready for review

#452 [55394] Updated locales with correct links and added title to source link
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#455 [55362] Fixed errors in Tigrinya texts
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R2.2, ready for review

#456 [55410] Updated link and display text for Smittestopp numbers source
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#457 [Android] Consent 1 - move sticky component to the bottom and make warning view edge to edge
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_five.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
Labels: R2.2, ready for review

#460 Fixed Urdu text direction in settings menu
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#459 [55228] update set languages text + all locales updated
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#463 Latest version of all texts
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#464 [55233] Android: Set layout direction of alertdialog according to selected language
  NDB.Covid19/NDB.Covid19.Droid/Utils/DialogUtils.cs
Labels: R2.2, ready for review

#433 [54926] Improved token validation in reporting flow
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ViewModels/QuestionnaireCountriesViewModelTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireCountriesViewModel.cs
Labels: R2.2, ready for review

#468 [55493] Key Figures: small letters in covid-19
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#471 [55504] Android + IOS: Unify link colors
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about_scroll.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHowItWorksActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: R2.2, ready for review

#466 Renamed file FHIStatisticsDTO.cs to CovidStatisticsDTO.cs to match the classname
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CovidStatisticsDTO.cs
Labels: R2.2, ready for review

#470 [55515] Fixed text direction errors in Urdu
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#462 Feature/53767 initial implementation of ExposureStateUpdatedAsync handler method + add print Buttons to DevTools
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/en_developer_tools.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperTools.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ENDeveloperTools/ENDeveloperToolsViewController.designer.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDailySummaryJsonHelper.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureWindowJsonHelper.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/JsonCompatibleExposureDailySummary.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/JsonCompatibleExposureWindow.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/DeveloperToolsService.cs
  NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/IDeveloperToolsService.cs
  NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/ReleaseToolsService.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
Labels: R3.0, ready for review

#473 [55543] IOS: Switch input for total downloads and positive shared last 7 days labels
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
Labels: R2.2, ready for review

#475 [55554] Update screenText for Somali
  NDB.Covid19/NDB.Covid19/Locales/so.json
Labels: R2.2, ready for review

#477 [55542] Updated language selection texts
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#476 [55555] Updated tigrinya texts
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R2.2, ready for review

#472 [55514] Phone crashes after entered bank ID, when the phone language is set to Arabic
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InformationAndConsentViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2.2, ready for review

#478 [55512] Update arabic language
  NDB.Covid19/NDB.Covid19/Locales/ar.json
Labels: R2.2, ready for review

#469 [55508] Added more information about the numbers in key numbers page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#467 Update Daily Numbers on return from background
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R2.2

#474 Android: Moved back buttons to the bottom of the screen reader traversal
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/messages_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_about.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_consents.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_help.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_how_it_works.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_four.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_one.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_three.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_page_two.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
Labels: R2.2, ready for review

#479 [55542] Updated set language texts
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2, ready for review

#480 [54709] 1 sec delay for Accessibility elements
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
Labels: R2.2, affects:ios, ready for review

#481 [iOS] Made labels that display total numbers in boxes not visible for release 2.2
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
Labels: R2.2, affects:ios, ready for merge

#483 Renamed statistics property to match json from backend
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/AppStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
Labels: R2.2, ready for review

#458 Updating README and CONTRIBUTING
  CONTRIBUTING.md
  README.md
Labels: R2.2, is:documentation, ready for review

#489 Added DSOS and AnonToken used for developer tools output when posting keys
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R2.2.1, ready for review

#484 [55596] Added line breaks to link texts
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2.1, ready for review

#491 New AnonymousTokens feature flag and updated property namings (#291)
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
Labels: R2.2.1, ready for merge

#490 [55716, 55508, 55511] Unhidden total numbers from key numbers page and added updated texts
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2.1, ready for review

#492 [R2.2.1] Android: Correct lines alignment
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R2.2.1, ready for review

#494 [55782] Fixed spelling error in Lithuanian text
  NDB.Covid19/NDB.Covid19/Locales/lt.json
Labels: R2.2.1, ready for review

#493 [55517] Implemented timed disable/enable of back buttons to prevent them being read first by voiceover
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/PageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
Labels: R2.2.1, ready for review

#495 Latest approved texts for R2.2.1
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2.1, ready for review

#496 [54769] Moved close button in settings menu to bottom of screen reader hierarchy
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.cs
Labels: R2.2.1, ready for review

#497 [55820] Removed colon in nynorsk text and fixed alignment in key numbers page
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2.1, ready for review

#498 Merge dev R2.2.1 into dev
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/PageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R2.2.1

#499 Merge dev into master for 2.2.1
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/PageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R2.2.1, ready for review

#500 Android: Fixed alignment issues. iOS: Fixed which label that gets focus in message page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
Labels: R2.2.1, ready for review

#501 Merge dev into master
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
Labels: R2.2.1, ready for review
