Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-04, with the labels that each got.

#502 [55511] Added new translations for key numbers explanation text
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2.2, ready for review

#503 [55967] Added a version check when displaying dialogs to avoid crash on Android 6.0
  NDB.Covid19/NDB.Covid19.Droid/Utils/DialogUtils.cs
Labels: R2.2.2, ready for review

#505 Proto update for EN API v2
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Proto/TemporaryExposureKeyBatch.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/Utils/DeveloperTools/DeveloperToolsService.cs
Labels: R3.0, ready for review

#504 [55817] Switched default date representation to nynorsk culture
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
Labels: R2.2.2, ready for review

#507 Increased version number to 2.2.2
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: R2.2.2, ready for review

#506 Added updated translations for key numbers page
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.2.2, ready for review

#508 Merge dev R2.2.2 into dev
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/DialogUtils.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
Labels: R2.2.2, ready for review

#509 [53767] DSC Integration with server
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/Models/DailySummaryConfigurationDTO.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R3.0, ready for review

#511 [53767] Android: Add DiagnosisKeysDataMapping
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/DiagnosisKeysDataMappingUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/ENDeveloperTools/ENDeveloperToolsActivity.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
Labels: R3.0, ready for review

#512 Fix bug 56194 and 56195
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
Labels: R2.2.2, ready for review

#514 Fix bugs 56212 and 56214
  NDB.Covid19/NDB.Covid19/Locales/ti.json
Labels: R2.2.2, ready for review

#515 Fix potential crash on language check
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
Labels: R2.2.2, ready for review

#516 [53767] Applying x100 multipliers for iOS where the system expects weights in percents and not multipliers
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
Labels: R3.0, ready for review

#517 [53767] Risk scoring EN API v2
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ExposureDetectedTests.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
  NDB.Covid19/NDB.Covid19/Models/DailySummaryConfigurationDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R3.0, ready for review

#518 Merge dev R2.2.2 into dev
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
Labels: R2.2.2

#520 Merging latest dev R2.2.2 to R3.0
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general_link.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_page.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/DialogUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsActivity.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/BaseViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage3/SettingsPage3ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/PageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageFourViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageOneViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageThreeViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/ChildViews/WelcomePageTwoViewController.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R3.0, ready for review

#521 Fix configuration for local nuget package
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/Nuget.config
Labels: R3.0, ready for review

#513 [55628] Android: add logging to submission flow
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Services/RemovedFromRecentDetectorService.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/AuthErrorUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/ErrorActivities/GeneralErrorActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/InformationAndConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/LoadingPageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnairePageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/RegisteredActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/LogDTO.cs
  NDB.Covid19/NDB.Covid19/Models/SQLite/LogSQLiteModel.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/Utils/LogUtils.cs
Labels: R3.0, ready for review

#523 Rework key validation on app for EN API v2
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/TransmissionRiskCalculationTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/UploadDIagnosisKeysHelperTests.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/UploadDiagnosisKeysHelper.cs
Labels: R3.0, ready for review

#524 [55628] iOS: add logging to submission flow new
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Main.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/LoadingPageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ErrorStatus/ErrorPageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: R3.0, ready for review

#527 Fix: Replace ExposureNotificationHandler with ExposureNotificationWebService for DataMappingUtils
  NDB.Covid19/NDB.Covid19.Droid/Utils/DiagnosisKeysDataMappingUtils.cs
Labels: R3.0, ready for review

#526 [55628] iOS: add extra methods to app delegate to detect life cycling of views
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/SceneDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/LoadingPageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireCountries/QuestionnaireCountriesViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ErrorStatus/ErrorPageViewController.cs
  NDB.Covid19/NDB.Covid19/Utils/MessagingCenterKeys.cs
Labels: R3.0, ready for review

#531 [53767] update configuration to use ScoreSum instead of MaximumScore
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ExposureDetectedTests.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/ExposureDetected/ExposureDetectedHelper.cs
  NDB.Covid19/NDB.Covid19/Models/DailySummaryConfigurationDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ENDeveloperToolsViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/ExposureNotificationWebService.cs
Labels: R3.0, draft, ready for review

#529 [56465] [Issue 40] Corrected log message on iOS ("Started login with ID porten")
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/InformationAndConsentViewController.cs
Labels: R3.0, ready for review

#530 [56472] [Issue 40] Android user opened app log message should only appear once per app lifetime
  NDB.Covid19/NDB.Covid19.Droid/MainApplication.cs
Labels: R3.0, ready for review

#438 Change NTP server
  NDB.Covid19/NDB.Covid19/Utils/NTPUtcDateTime.cs
Labels: R3.0, ready for review

#534 Handle EN api exception instead of rethrowing
  NDB.Covid19/NDB.Covid19.Droid/Services/PermissionsBroadcastReceiver.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/LoadingPageActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Main.cs
  NDB.Covid19/NDB.Covid19/ExceptionExtensions.cs
  NDB.Covid19/NDB.Covid19/Utils/DeviceUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
Labels: R3.0, ready for review
