Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-02, with the labels that each got.

#308 Merge dev into dev-R2.0
  NDB.Covid19/NDB.Covid19.Droid/Utils/AccessibilityUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Utils/PermissionUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageFourFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageOneFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageThreeFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageTwoFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19.iOS/appcenter-pre-build.sh
  NDB.Covid19/NDB.Covid19/Configuration/OAuthConf.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: ready for review

#307 [53128] iOS: Fixed issue where screen reader read text twice
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
Labels: R2.1, ready for review

#309 Fixed issues with UI on About page on iOS
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5ViewController.cs
Labels: R2.1, ready for review

#311 Updated layout and added texts to consent 3 page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/countries_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
Labels: R2.0, ready for review

#316 Merge dev into dev r2.0
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
Labels: ready for review

#317 Merge dev-R2.0 into dev-R2.1
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/consent_info.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/countries_consent.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_bullet.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/CountriesConsentActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/AuthenticationFlow/QuestionnaireCountriesSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InitializerActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageConsentsActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.Test/Helpers/ZipDownloaderHelper.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PullKeysParamsTest.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/PullKeysTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ExposureNotification/ReapproveConsentsNotificationTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/Utils/LanguageTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/ViewModels/QuestionnaireCountriesViewModelTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/CountriesConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/Consent.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNew.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Welcome/WelcomePageWhatIsNewViewController.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/CountryDetailsDTO.cs
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/ConsentViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/CountriesConsentViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InitializerViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireCountriesViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
  NDB.Covid19/NDB.Covid19/WebServices/CountryListService.cs
  NDB.Covid19/NDB.Covid19/WebServices/ExposureNotification/PullKeysParams.cs
Labels: ready for review

#281 [feature/52940] Android: Added extra notification channels for separating different notifications
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/strings.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/LocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/ViewModels/NotificationChannelsViewModel.cs
Labels: R2.1, ready for review

#320 Fixed build errors
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomePageWhatIsNewActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelectionViewController.cs
Labels: R2.1, ready for review

#303 [Cherry-pick] [53168] Prevent ReportedDate beeing too much into the past or future
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19.Test/Tests/Utils/NTPDateTimeTests.cs
  NDB.Covid19/NDB.Covid19.Test/Tests/WebServices/AnonymousTokenServiceTest.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/ExposureNotifications/Helpers/FetchExposureKeys/FetchExposureKeysHelper.cs
  NDB.Covid19/NDB.Covid19/Models/Logging/LogDeviceDetails.cs
  NDB.Covid19/NDB.Covid19/Models/PersonalDataModel.cs
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/Utils/NTPUtcDateTime.cs
  NDB.Covid19/NDB.Covid19/WebServices/AnonymousTokenService.cs
Labels: R2.1, cherry-pick, ready for review

#323 [53440] iOS: Increased spacing at the bottom of how it works page
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage2/SettingsPage2.storyboard
Labels: R2.1, ready for review

#324 [53496] Fixed an issue where the text on the accessibility statement link was not updating
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsPage5ViewModel.cs
Labels: R2.1, ready for review

#312 iOS: Fix unassigned assets
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxFilled.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Assets.xcassets/checkboxUnfilled.imageset/Contents.json
Labels: R2.1, ready for review

#297 [52939] Add support for iOS 12.5 to Smittestopp
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.iOS/AppDelegate.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Managers/iOSLocalNotificationsManager.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/BackgroundServiceHandler.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/LoadingPageViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompleted.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/MessagePage/MessagePageCell.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage5/SettingsPage5.storyboard
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
Labels: R2.1, affects:ios, is:enhancement, is:inProgress, ready for review

#326 [Feature/53082] Added arrow to start page button
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_start_page_arrow.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_start_page_arrow.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_start_page_arrow.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxxhdpi/ic_start_page_arrow.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_start_page_arrow_right.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/layout_with_launcher_button_ag_api.xml
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/StartArrow.imageset/Contents.json
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/StartArrow.imageset/starticon@1x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/StartArrow.imageset/starticon@2x.png
  NDB.Covid19/NDB.Covid19.iOS/Resources/Assets.xcassets/StartArrow.imageset/starticon@3x.png
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
Labels: R2.1, ready for review

#325 [Feature/52910, 52907, 52913, 52919, 52916] Added translated locales to the code basis
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.1, ready for review

#328 [53618] Adjusted language selection page to support horizontal view on smaller screens
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/language_selection.xml
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelection.storyboard
Labels: R2.1, ready for review

#330 [53624] Deleted unnecessary accessibility label with wrong text
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompletedViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2.1, ready for review

#333 [53621] Adjusted start page to better resize to horizontal view
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
Labels: R2.1, ready for review

#332 [53625] Adjusted constraints in UploadCompleted page to better support horizontal layout
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/UploadCompleted.storyboard
Labels: R2.1, ready for review

#331 Added updated nynorsk texts
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.0, ready for review

#336 [53665, 53672] Updated to the latest texts
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.0, ready for review

#334 [53589] Changed WorkManager to keep existing periodic work instead of replacing
  NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
Labels: R2.1, ready for review

#329 [53626] iOS: Deleted unnecessary accessibility label with wrong text
  NDB.Covid19/NDB.Covid19.iOS/Views/AuthenticationFlow/QuestionnaireViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/ViewModels/QuestionnaireViewModel.cs
Labels: R2.1, ready for review

#339 R2.0 - Text update for "What's new" page
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.0, ready for review

#342 Merge from dev to master for R2.0 review
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.0, ready for merge

#343 [52686] Fixed UI bug where arrow and text where overlapping
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/Initializer.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/InizializerViewController.cs
Labels: R2.1, ready for review

#337 [Feature/53096] Initial implementation of Daily Numbers on both platforms
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_bottom.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_mid.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/counter_background_daily_numbers_top.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable/ic_start_logo_ag_api.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Utils/AuthErrorUtils.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersLoadingPage.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/NDB.Covid19.iOS.csproj
  NDB.Covid19/NDB.Covid19.iOS/Utils/AuthErrorUtils.cs
  NDB.Covid19/NDB.Covid19.iOS/Utils/StyleUtil.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersLoading.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersLoadingViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersLoadingViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatus.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Interfaces/XamarinEssentials.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/AppStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/DailyNumbersDTO.cs
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/FHIStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/Utils/MessagingCenterKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/ErrorViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/InfectionStatusViewModel.cs
  NDB.Covid19/NDB.Covid19/WebServices/DailyNumbersWebService.cs
Labels: R2.2, ready for review

#345 [53254] android: Updated the accessibility announcements such that they are read aloud in correct order
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
Labels: R2.1, ready for review

#346 Added updated languages from Excel sheet
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R2.1, ready for review

#347 [53774] Android: Adjusted UI on infection status page in regard to todays numbers
  NDB.Covid19/NDB.Covid19.Droid/NDB.Covid19.Droid.csproj
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-hdpi/ic_todays_numbers.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xhdpi/ic_todays_numbers.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/drawable-xxhdpi/ic_todays_numbers.png
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/infection_status.xml
Labels: R2.2, ready for review

#348 [54075] Fixed .no in the email address being read wrong in NB and EN, other languages remain unchanged
  NDB.Covid19/NDB.Covid19.iOS/Views/ConsentView/ConsentViewController.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/ViewModels/ConsentViewModel.cs
Labels: R2.1, ready for review

#351 [54085] Added missing bokmål word in "How Smittestopp Works"
  NDB.Covid19/NDB.Covid19/Locales/nb.json
Labels: R2.1, ready for review

#354 Updated polish language
  NDB.Covid19/NDB.Covid19/Locales/pl.json
Labels: R2.1, ready for review

#353 [54226] fix bug about polish link on how it works and bug for screenreader onboarding pages
  NDB.Covid19/NDB.Covid19.Droid/Views/Welcome/WelcomeActivity.cs
Labels: R2.1, ready for review

#359 [54236] Android: fixed space issue on what is new page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/welcome_what_is_new.xml
Labels: R2.1, ready for review

#361 [iOS] Removed arabic, tigrinya and urdu from language selection
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelectionViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: R2.1, ready for review

#360 Hide Arabic language
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/language_selection.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/LanguageSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
Labels: R2.1, ready for review

#362 [54328] Update somali text for symptoms header
  NDB.Covid19/NDB.Covid19/Locales/so.json
Labels: R2.1, ready for review

#364 [53778] Add screen reader support for added UI element to main page
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R2.2, ready for review

#350 [53776] Android + shared code: updated the todays numbers page with new elements, correct color etc.
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/colors.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/dimens.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/values/styles_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Models/DTOsForServer/FHIStatisticsDTO.cs
  NDB.Covid19/NDB.Covid19/PersistedData/LocalPreferencesHelper.cs
  NDB.Covid19/NDB.Covid19/PersistedData/PreferencesKeys.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R2.2, ready for review

#367 [54396] Polish: Covid-19 with capital letters on "Consent and privacy…
  NDB.Covid19/NDB.Covid19/Locales/pl.json
Labels: R2.1, ready for review

#370 [54074] Set text on Help and support page to be static text so it won't be split by accessibility VoiceOver
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPage4/SettingsPage4.storyboard
Labels: R2.1, ready for review

#374 [53779] [53783] iOS: Added screen reader support main page + Data fetching indicator for todays numbers
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersLoadingViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: R2.2, ready for review

#366 [Android] Screen reader support for the new page "Dagens tall" (all languages)
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R2.2, ready for review

#382 [54282, 54234, 54235] Fixed multiple link and alignment issues with Arabic on Android
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/ConsentSettingPageFragment.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsHelpActivity.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
Labels: R2.2, ready for review

#381 [54392] Fixed email address pronounciation in Nynorsk
  NDB.Covid19/NDB.Covid19/Locales/nn.json
Labels: R2.2, ready for review

#380 [Feature/54476, 54475, 54481, 54482, 54483, 54484, 54485] iOS: Lithuanian support
  NDB.Covid19/NDB.Covid19.Test/Tests/Utils/DateUtilsTests.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelection.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelectionViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelectionViewController.designer.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettings.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.designer.cs
  NDB.Covid19/NDB.Covid19/Configuration/Conf.cs
  NDB.Covid19/NDB.Covid19/Enums/SettingsLanguageSelection.cs
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/NDB.Covid19.csproj
  NDB.Covid19/NDB.Covid19/ViewModels/LanguageSelectionViewModel.cs
  NDB.Covid19/NDB.Covid19/ViewModels/SettingsGeneralViewModel.cs
Labels: R2.2, ready for review

#384 [53776] Android: removed death number from daily numbers page
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/activity_daily_numbers.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
Labels: R2.2, ready for review

#383 [54462-54474] Re-add Urdu, Tigrinya and Arabic
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/language_selection.xml
  NDB.Covid19/NDB.Covid19.Droid/Resources/layout/settings_general.xml
  NDB.Covid19/NDB.Covid19.Droid/Views/LanguageSelectionActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Settings/SettingsGeneralActivity.cs
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19.iOS/Views/Initializer/LanguageSelectionViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/Settings/SettingsPageGeneral/SettingsPageGeneralSettingsViewController.cs
Labels: R2.2, ready for review

#385 [Feature/53772] Enabled landscape mode in Daily numbers page
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/DailyNumbers/DailyNumbersLoadingPage.cs
Labels: R2.2, ready for review

#379 [53794] IOS: Changed navigation from daily numbers error page, such that user i correctly navigated to main page
  NDB.Covid19/NDB.Covid19.iOS/Views/InfectionStatus/InfectionStatusViewController.cs
Labels: R2.2, ready for review

#386 [53777] iOS: Add new page "Dagens tall" - new UI changes
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbers.storyboard
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.cs
  NDB.Covid19/NDB.Covid19.iOS/Views/DailyNumbers/DailyNumbersViewController.designer.cs
Labels: R2.2, ready for review
