Repository folkehelseinstituttet/Fhi.Smittestopp.App, pull requests merged in 2021-07, with the labels that each got.

#571 [Bugfix] - Android - fixed alignment of date for new messages
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
Labels: R3.2

#572 [59225] bugfix - Spelling error on key figures page Lithuanian
  NDB.Covid19/NDB.Covid19/Locales/lt.json
Labels: R3.2, ready for review

#573 [59239] [Bugfix] - Somali spellings errors on key figures page
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R3.2, ready for review

#574 [Bugfix] - polish language text change in Key figures page
  NDB.Covid19/NDB.Covid19/Locales/pl.json
Labels: R3.2, ready for review

#576 [59315, 59312, 59316] Bugfix Urdu text
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R3.2, ready for review

#578 [59311] Bugfix Urdu date text on message page
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R3.2, ready for review

#579 [59313] Bugfix - Activation button fix
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
Labels: R3.2, ready for review

#580 Merge dev R3.2 into dev
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R3.2, ready for review

#581 Merge dev into master
  NDB.Covid19/NDB.Covid19.Droid/Views/InfectionStatus/InfectionStatusActivity.cs
  NDB.Covid19/NDB.Covid19.Droid/Views/Messages/MessagesAdapter.cs
  NDB.Covid19/NDB.Covid19.Test/NDB.Covid19.Test.csproj
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
  NDB.Covid19/NDB.Covid19/Utils/DateUtils.cs
  NDB.Covid19/NDB.Covid19/ViewModels/DailyNumbersViewModel.cs
Labels: R3.2, ready for review

#583 Increased version number to 3.2.1
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
Labels: R3.2.1, ready for review

#584 Json language text change
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R3.2.1, ready for review

#585 Merge dev R3.2.1 into dev
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R3.2.1, ready for review

#586 Merge dev into master
  NDB.Covid19/NDB.Covid19.Droid/Properties/AndroidManifest.xml
  NDB.Covid19/NDB.Covid19.iOS/Info.plist
  NDB.Covid19/NDB.Covid19/Locales/ar.json
  NDB.Covid19/NDB.Covid19/Locales/en.json
  NDB.Covid19/NDB.Covid19/Locales/lt.json
  NDB.Covid19/NDB.Covid19/Locales/nb.json
  NDB.Covid19/NDB.Covid19/Locales/nn.json
  NDB.Covid19/NDB.Covid19/Locales/pl.json
  NDB.Covid19/NDB.Covid19/Locales/so.json
  NDB.Covid19/NDB.Covid19/Locales/ti.json
  NDB.Covid19/NDB.Covid19/Locales/ur.json
Labels: R3.2.1, ready for review
